# Generated by Django 3.1.6 on 2021-02-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان انگلیسی')),
            ],
            options={
                'verbose_name': 'دسته بندی کار',
                'verbose_name_plural': 'دسته بندی های کار',
            },
        ),
    ]
