# Generated by Django 3.1.6 on 2021-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'تماس کاربر',
                'verbose_name_plural': 'تماس های کاربران',
            },
        ),
    ]
