# Generated by Django 3.1.6 on 2021-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده / نشد'),
        ),
    ]
