# Generated by Django 3.1.6 on 2021-02-18 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
