# Generated by Django 3.1.6 on 2021-02-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_work', '0003_auto_20210218_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Works',
        ),
    ]
