# Generated by Django 3.1.6 on 2021-02-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_work', '0005_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
