# Generated by Django 3.1.6 on 2021-02-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_work_category', '0001_initial'),
        ('site_work', '0006_works_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='categories',
            field=models.ManyToManyField(blank=True, to='site_work_category.WorksCategory', verbose_name='دسته بندی کار'),
        ),
    ]
