# Generated by Django 3.1.6 on 2021-02-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_work', '0007_works_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='categories',
        ),
    ]
