# Generated by Django 3.1.6 on 2021-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_work', '0008_remove_works_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='عنوان انگلیسی دسته بندی'),
        ),
    ]
