# Generated by Django 3.1.6 on 2021-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_work_category', '0001_initial'),
        ('site_work', '0009_works_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='site_work_category.WorksCategory', verbose_name='دسته بندی ها'),
        ),
    ]
