# Generated by Django 3.1.6 on 2021-02-16 18:09

from django.db import migrations, models
import site_about_us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='نام', max_length=250, verbose_name='نام')),
                ('last_name', models.CharField(default='نام خانوادگی', max_length=250, verbose_name='نام خانوادگی')),
                ('short_description', models.CharField(default='توضیح کوتاه', max_length=100, verbose_name='توضیح کوتاه')),
                ('email', models.EmailField(default='ایمیل', max_length=100, verbose_name='ایمیل')),
                ('phone', models.CharField(default='شماره تماس', max_length=150, verbose_name='شماره تماس')),
                ('date_of_birth', models.CharField(default='تاریخ تولد', max_length=60, verbose_name='تاریخ تولد')),
                ('place_of_birth', models.CharField(default='مکان تولد', max_length=100, verbose_name='مکان تولد')),
                ('about_text', models.TextField(default='توضیحات درباره من', verbose_name='توضیحات درباره من')),
                ('facebook', models.CharField(default='facebook', max_length=40, verbose_name='آیدی فیسبوک')),
                ('twitter', models.CharField(default='twitter', max_length=40, verbose_name='آیدی توییتر')),
                ('instagram', models.CharField(default='instagram', max_length=40, verbose_name='آیدی اینستاگرام')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=site_about_us.models.upload_image_path, verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
    ]
