# Generated by Django 3.1.6 on 2021-02-16 19:02

from django.db import migrations, models
import site_about_us.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(max_length=400, verbose_name='توضیحات')),
                ('about_work_image', models.ImageField(blank=True, null=True, upload_to=site_about_us.models.upload_image_path_about_work, verbose_name='آیکون')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'درباره من کاری که انجام می دهم',
                'verbose_name_plural': 'درباره من کارهایی که انجام می دهم',
            },
        ),
    ]
