# Generated by Django 3.1.6 on 2021-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_about_us', '0002_aboutwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='facebook',
            field=models.CharField(default='facebook', max_length=40, verbose_name='آیدی لینکدین'),
        ),
    ]
