# Generated by Django 3.1.6 on 2021-02-17 04:03

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import site_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان', max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(default='توضیحات کوتاه', max_length=400, verbose_name='توضیحات کوتاه')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بدنه اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=site_blog.models.upload_image_path, verbose_name='تصویر اصلی')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
