# Generated by Django 3.1.6 on 2021-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
