# Generated by Django 3.1.6 on 2021-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_blog_category', '0001_initial'),
        ('site_blog', '0003_auto_20210217_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='categories',
            field=models.ManyToManyField(blank=True, to='site_blog_category.BlogsCategory', verbose_name='دسته بندی وبلاگ'),
        ),
    ]
