# Generated by Django 3.1.6 on 2021-02-19 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_blog', '0004_blogs_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='BlogsLikes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
